language: cpp

matrix:
  include:
    - env: NAME="Linux Build"
      os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      script: ./.travis/linux-build.sh
    - env: NAME="macOS Build"
      os: osx
      sudo: false
      osx_image: xcode10
      script: ./.travis/macos-build.sh
    - env: NAME="Windows Build"
      os: windows
      script: ./.travis/windows-build.sh
